import {
  Instagram,
  Youtube,
  Twitter,
  Globe,
  Music,
  Github,
  Facebook,
  Linkedin,
  Mail,
  Phone,
  Twitch,
  Dribbble,
  Figma,
  Gitlab,
  Slack,
  Chrome,
  Codepen,
  Cloud,
  MapPin,
  Camera,
  Calendar,
  Coffee,
  ShoppingCart,
  FileText,
  Heart,
  Star,
  Play,
  Send,
  MessageCircle,
  Book,
  Cpu,
  Shield,
  User,
  Users,
  Briefcase,
  Building,
  Radio,
  Monitor,
  Smartphone,
  Wifi,
  Rss,
  Zap,
  Rocket,
  Globe2,
} from "lucide-react";

export const iconOptions = [
  { value: "Telegram", label: "Telegram", Icon: Send },
  { value: "Instagram", label: "Instagram", Icon: Instagram },
  { value: "Youtube", label: "YouTube", Icon: Youtube },
  { value: "Twitter", label: "Twitter/X", Icon: Twitter },
  { value: "Globe", label: "Website", Icon: Globe },
  { value: "Music", label: "Music", Icon: Music },
  { value: "Github", label: "GitHub", Icon: Github },
  { value: "Facebook", label: "Facebook", Icon: Facebook },
  { value: "Linkedin", label: "LinkedIn", Icon: Linkedin },
  { value: "Mail", label: "Email", Icon: Mail },
  { value: "Phone", label: "Phone", Icon: Phone },
  { value: "Twitch", label: "Twitch", Icon: Twitch },
  { value: "Dribbble", label: "Dribbble", Icon: Dribbble },
  { value: "Figma", label: "Figma", Icon: Figma },
  { value: "Gitlab", label: "GitLab", Icon: Gitlab },
  { value: "Slack", label: "Slack", Icon: Slack },
  { value: "Chrome", label: "Chrome", Icon: Chrome },
  { value: "Codepen", label: "CodePen", Icon: Codepen },
  { value: "Cloud", label: "Cloud", Icon: Cloud },
  { value: "MapPin", label: "Location", Icon: MapPin },
  { value: "Camera", label: "Camera", Icon: Camera },
  { value: "Calendar", label: "Calendar", Icon: Calendar },
  { value: "Coffee", label: "Coffee", Icon: Coffee },
  { value: "ShoppingCart", label: "Shop", Icon: ShoppingCart },
  { value: "FileText", label: "Document", Icon: FileText },
  { value: "Heart", label: "Like / Love", Icon: Heart },
  { value: "Star", label: "Favorite / Star", Icon: Star },
  { value: "Play", label: "Play", Icon: Play },
  { value: "MessageCircle", label: "Chat", Icon: MessageCircle },
  { value: "Book", label: "Book / Article", Icon: Book },
  { value: "Cpu", label: "Tech / CPU", Icon: Cpu },
  { value: "Shield", label: "Security", Icon: Shield },
  { value: "User", label: "User", Icon: User },
  { value: "Users", label: "Users", Icon: Users },
  { value: "Briefcase", label: "Work / Business", Icon: Briefcase },
  { value: "Building", label: "Company / Building", Icon: Building },
  { value: "Radio", label: "Podcast / Radio", Icon: Radio },
  { value: "Monitor", label: "Monitor", Icon: Monitor },
  { value: "Smartphone", label: "Mobile", Icon: Smartphone },
  { value: "Wifi", label: "Wi-Fi", Icon: Wifi },
  { value: "Rss", label: "RSS Feed", Icon: Rss },
  { value: "Zap", label: "Zap / Lightning", Icon: Zap },
  { value: "Rocket", label: "Startup / Rocket", Icon: Rocket },
  { value: "Globe2", label: "Global", Icon: Globe2 },
];
